services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # MinIO API port
      - "9001:9001"  # MinIO console port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped


  kafka:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kafka-kraft-ui
    ports:
      - "9092:9092"  # Kafka broker
      - "8081:8080"  # Kafka UI
      - "8765:8765"  # WebSocket
      - "3000:3000"  # Unity Catalog
    volumes:
      - ./s3d_producer:/home/kafkauser/app  # volume mount
      - ./kafka_data:/var/lib/kafka/data
    environment:
      - MINIO_ENDPOINT=http://minio:9000  # Use MinIO service name
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    depends_on:
      - minio  # Only if your scripts depend on MinIO
    restart: unless-stopped

#  ui:
#    build:
#      context: ui/
#      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"





